---
title: terranceleeg-designs.tld
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: redcarpet
highlighter: pygments
exclude:
- node_modules
- gulpfile.js
- package.json
email: terranceleeg@gmail.com
description: A small and simple site I made to test out Jekyll. Watch out! I'm going
  to make a material design theme next!
baseurl: http://terranceleeg-designstld.siteleaf.net/
url: http://terranceleeg-designstld.siteleaf.net/
twitter: 
facebook: 
google: 
author: Nina Petropoulos
authorBio: A English major by day, a musician by night, and a web developer because
  of the summer I was bored - my name's Nina and I hope you enjoy my Hello Portland
  theme, the second theme I've made with Jekyll.
